watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 12
      left: 11
      bottom: 4
      right: 11
    widgets:
      left:
        [
          "home",
          "bin",
          "update_check",
          "cpu",
          "memory",
          "traffic",

        ]
      center:
        [
          "apps",          
          "clock",
          "weather",
          "notes"          
        ]
      right:
        [
          "cava",
          "media",
          "disk",
          "power_menu"
        ]
widgets:
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#D3C6AA"
      gradient_color_1: '#bbb099'
      gradient_color_2: '#bbb099'
      bars_number: 12
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 0
      framerate: 25
      sleep_timer: 30
      hide_empty: false
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "༼ つ◕_◕ ༽つ"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\pizza\\Downloads"}
        - { title: "Documents", path: "C:\\Users\\pizza\\Documents"}
        - { title: "Games" , path: "C:\\Users\\pizza\\Desktop\\Games~Porrtable"}
        - { title: "Pictures", path: "C:\\Users\\pizza\\OneDrive\\Pictures"}
        - { title: "Videos", path: "C:\\Users\\pizza\\Videos"}
        - { title: "Music~Foobar", path: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\foobar2000.lnk"}
        - { title: "Streamio", path: "C:\\Users\\pizza\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Stremio.lnk"}
        - { title: "Steam", path: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk"} 
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title}"
      hide_empty: false
      callbacks:
       on_left: "toggle_media_menu"
       on_middle: "do_nothing"
       on_right: "toggle_label"
      max_field_size:
        label: 45
        label_alt: 125
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
       blur: true
       round_corners: true
       round_corners_type: "normal"
       border_color: "#7e8f85"
       alignment: "right"
       direction: "down"
       offset_top: 6
       offset_left: 0
       thumbnail_corner_radius: 8
       thumbnail_size: 160
       max_title_size: 80
       max_artist_size: 80
       show_source: true
      media_menu_icons:
       play: "\ue768"
       pause: "\ue769"
       prev_track: "\ue892"
       next_track: "\ue893"
      label_shadow:
       enabled: true
       color: "black"
       radius: 1
       offset: [ 1, 1 ]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a, %d %b %H:%M:%S}"
      label_alt: "<span>\ue769</span>{%I:%M %p}"
      timezones: [] #Looking up time zone info from registry
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {conditions} {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '1f01f0b97fbb4050b95212816252106'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Brazil Goiania 74840-530"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#7e8f85"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: False
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        lock: ["\uf023","Lock"]
        cancel: ["\udb81\udf3a","Cancel"]

  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true 
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "#7e8f85"
          alignment: "right"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 5
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 180
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb82\udcfa</span>    \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 3000
      callbacks:
        on_left: 'toggle_label'
        on_right: 'exec cmd /c Taskmgr'
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
    container_padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    menu:
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#7e8f85"
      alignment: "right"
      direction: "down"
      offset_top: 6
      offset_left: 0
      max_title_size: 150
      show_date_time: true
    icons:
      note: "\udb82\udd0c"
      delete: "\ue20d"
    callbacks:
      on_left: "toggle_menu"
      on_middle: "do_nothing"
      on_right: "toggle_label"
    label_shadow:
      enabled: true
      color: "black"
      radius: 3
      offset: [ 1, 4 ]
  bin:
    type: "yasb.recycle_bin.RecycleBinWidget"
    options:
      label: "<span>{icon}</span>({items_size})"
      icons:
        bin_empty: "\udb82\ude7a"
        bin_filled: "\udb82\ude79"
      container_padding:
        left: 0
        top: 0
        right: 0
        bottom: 0
      callbacks:
        on_left: "open_bin"
        on_right: "toggle_label"
        on_middle: "empty_bin"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label: "{data}"
      app_list:
        - { icon: "\u26A1" ,launch: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Microsoft Edge.lnk" }
        - { icon: "\uf0ac" ,launch: "C:\\Users\\pizza\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Opera GX Browser.lnk" } # Opera Icon        
        - { icon: "\uf489", launch: "wt" }    
        - { icon: "\uf1ff",launch: "C:\\Users\\pizza\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord.lnk" }
        - { icon: "\udb82\ude1e",launch: "C:\\Users\\pizza\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Visual Studio Code\\Visual Studio Code.lnk" }    